### ISSUE TITLE
Encoding description

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19110#10]
Package "Encoding description" and Annex C - are they needed, or do we just need Annex I?

**Comment by jetgeo** [comment]
Comment from Dave Danko (2015-08-06): I would suggest we delete annex I and retain Annex C. move up some of the references in I to C if needed

**Comment by jetgeo** [comment]
I agree that the content of Annex I can be merged into Annex C

**Comment by DaveDanko** [comment]
I deleted annex I
