### ISSUE TITLE
Requirement for l.o.a. feature type

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19110#15]
Section 6.1 if level of abstraction is feature type, shouldn't there be a requirement for at least one featuretype in a catalogue?  This is inconsistent with cardinality of 0..\* on aggregatation from featureCatalogue to FeatureType in the UML.

**Comment by jetgeo** [comment]
I would say that I agree to this. Quote: "The basic level of abstraction in a feature catalogue SHALL be the feature type."
I believe the association from FC_FeatureCatalogue to FC_FeatureType should be 1..*
![fig b1 - conceptual model of a feature catalogue](https://cloud.githubusercontent.com/assets/7501876/9274805/f0e08064-4298-11e5-8078-af2168cbbbcf.png)

**Comment by DaveDanko** [comment]
I agree you should change the featureType constraint to 1..\* 
I'm concerned about all the bidirectional relationships, I can see them being used with FC_FeatureType and FC_FeatureRelationship but do we need them elsewhere? or even a roll name/constraint on one (non-directed) end  of the relationship? doesn't this create a lot of unused elements?

**Comment by jetgeo** [comment]
Changed multiplicity. Bidirectional relationships need further discussion.
