### ISSUE TITLE
Requirement for FC_PropertyType

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19110#16]
section 6.2.2.  The only required property on FC_PropertyType is memberName; this is not consistent with the requirement "The feature catalogue SHALL include definitions and descriptions of all feature attributes and feature associations.."  Why definition and description-- none of the classes have both of these properties, and how are they distinguished?

**Comment by jetgeo** [comment]
Cardinality is also mandatory. But I agree, description is not an attribute on these classes. Definition is mandatory if not provided by definition source, so one may say that one is OK.
Suggested change: "The feature catalogue SHALL include definitions of all feature attributes and feature associations.."
The same change should also be applied to the requirement before this one: "The feature catalogue SHALL include definitions and descriptions of all feature types contained in the data"

Also, the requirements list (6.3) must be updated according to this.

**Comment by DaveDanko** [comment]
I'm getting lost in all these different lists of changes and what's been fixed
but shouldn't "definition" in FC_FeatureType be mandatory?

**Comment by jetgeo** [comment]
Definition for FC_FeatureType is mandatory through the constraint. It shall either be provided through a definition source, or in the definition attribute.

**Comment by jetgeo** [comment]
...and I can understand your confusion, Dave. I was beginning to get lost myself, so I tried to collect all known issues in this list. Sorry if it made thing even worse :).

**Comment by DaveDanko** [comment]
thanks, I forgot to check constraints

**Comment by DaveDanko** [comment]
I made these changes to 6.2.2: 
Req/type-definitions: The feature catalogue SHALL include definitions **and descriptions** of all feature types contained in the data, 
Req/property-definitions: The feature catalogue SHALL include definitions **and descriptions**  of all feature attributes and feature associations contained in the **data that are associated with**_catalogue_ **each feature type.** (attributes and assoc are optional but if included must have definitions)
bold = delete; italic = added

**Comment by jetgeo** [comment]
I believe this is ok now.
