### ISSUE TITLE
Dependency with GML

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19110#20]
A dependency with GML is created by implementation of the 'unitOfMeasure' property value using the GML UnitOfMeasure class; this could also be implemented by modifying gco. The 19103:2015 'interface' for UnitOfMeasure is a uomIdentifier property, which is already defined as a type in gco; we jus need to add an element and property type definition in gco (won't break anything else) and then we can implement FC_FEatureAttribute.valueMeasurementUnit.UnitOfMeasure with uomIdentifier, and avoid any GML dependency from the ISO19110 XML, which is a good thing for simplifying...

**Comment by jetgeo** [comment]
I think I have all ready changed this: 
Feature Cataloging.FC_FeatureAttribute.valueMeasurementUnit (Data type: UnitOfMeasure from package ISO TC211.ISO 19103 All.ISO 19103:2015 Conceptual schema language.Measure types)

**Comment by jetgeo** [comment]
Done?

**Comment by smrgeoinfo** [comment]
Yes, gco:UnitOfMeasure is used. All dependency on GML is gone.
