### ISSUE TITLE
Encoding - reference to 19103, 19115 and 19139

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19110#22]
Figure C.1 in the HM model is not identical to the one in the document. In the model, references goes to ISO19103:2005 (gco), ISO19115:2006 (gmd) and 19139 (gmx). In the document, the version of the referenced standards are left out. 
Suggested change: 
- Update the figure in HM to correct versions of 19103 (2015) and 19115 (2014). What about 19139? 
- Insert new figure in the document, from the HM

**Comment by DaveDanko** [comment]
Our problem is that this document was written before ISO1115-3 existed. it references 19139 and uses the gmx namespace which is not used in 19115-3 (replaced by cat and others?). also on the http://standards.iso.org/iso/19110/ there is the addition of fcc which is not used/referenced in this document. I propose that this document be written to work with both 39 and 15-3 if possible. Annex C should have two parts one using 19139 (gmo, gmx, gco) and the other 19115-3.  Can we add 19115-3 to the references even though it is not an IS? 
Steve/Ted can you help?

**Comment by DaveDanko** [comment]
forget my suggestion above - Annex C needs to be completely rewritten - referencing only the encoding rules in 19139 but implementing 19115-3 and using all new name spaces - abstract classes could also be added here solving Steve's issue #21 

Steve or Ted would be the best ones to do that.

**Comment by jetgeo** [comment]
The whole package "Encoding Description" should be removed from the conceptual model. Implementation specific models should be in the implementation model(s). 
If there shall be any figure in Annex C for illustrating the encoding, we should use the "Package dependencies" figures from the implementation model.

**Comment by jetgeo** [comment]
Deleted encoding package from the conceptual model in EA. Still some work left on Annex C, but closing this issue.
