### ISSUE TITLE
Missing data type connections

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19110#23]
Missing data type connection for attribute: FC_AssociationRole.cardinality (Data type: Multiplicity)  
Missing data type connection for attribute: FC_AssociationRole.isOrdered (Data type: Boolean)  
Missing data type connection for attribute: FC_AssociationRole.isNavigable (Data type: Boolean) 
Missing data type connection for attribute: FC_FeatureType.isAbstract (Data type: Boolean)  
Missing data type connection for attribute: FC_InheritanceRelation.uniqueInstance (Data type: Boolean)  
Missing data type connection for attribute: FC_PropertyType.cardinality (Data type: Multiplicity)

**Comment by smrgeoinfo** [comment]
Are these the links that need to be established in the EA UML model to get the XML build to work?

**Comment by jetgeo** [comment]
Yes, these are the attributes that aren't connected properly to a type. I will fix them next week, didn't have time to do it today.

**Comment by jetgeo** [comment]
The data type "Multiplicity" is removed from the new 19103. Not sure what to do with that.

**Comment by smrgeoinfo** [comment]
Maybe we have to define the enumeration in 19110?

**Comment by jetgeo** [comment]
I've had a discussion with Kent Johnsrud and Simon Cox on this issue, and we have agreed that the best sollution is to add a new Multiplicity type to 19109, similar to the one from 19103:2005. 
Simon have added the new type to 19109, and I have connected the 19110 attributes to this type. But we still have the issue https://github.com/ISO-TC211/ISO19110/issues/11.
