### ISSUE TITLE
note referencing 19115-3 in fig B.1

### ISSUE THREAD

**Issue by DaveDanko** [ISO-TC211/ISO19110#26]
I hate opening this while trying to close all the issues. this is actually two issues in referencing 19115-3
1. concerning the note "Import from cat namespace defined in ISO19115-3" in Fig B.1
   19115-3 is not referenced by this document
   CT_Catalogue is not defined in 19115-3, however it is defined in 19139:2007 which is referenced by this standard. Hopefully it will stay and be defined in the next version of 19139?
   Shouldn't EA have provided that reference in the class header?
   Suggest changing this to either a dashed class outline or with a dashed box around the CT_Catalogue class with a note "from CT_Catalogue" or reimporting it so it shows reference to where it came from.
2. Also note that we've added a reference to 19115-3 in C.1 which also has an incomplete sentence!!
   should we remove Steve's updates or complete the sentence and add 19115-3 to references?

**Comment by jetgeo** [comment]
1) The version of figure B.1 with the note has been replaced by a new version, without the note but with a automatic namespace reference, and also without the abstract classes for modularization. 
2) I believe we should keep the the first sentence "using the patterns for decoupling XML namespaces outlined in ISO19115-3", and add 19115-3 to references. The last sentence "The schema implementation implements" should be removed.

**Comment by DaveDanko** [comment]
Done
