### ISSUE TITLE
Abstract classes for modularization

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19110#5]
Figure B.1: The implementation model has got the abstract classes for modularization. Should they be included in the conceptual model too?

**Comment by jetgeo** [comment]
Comment from Dave Danko (2015-08-06): Figure B.1 – I don’t think you should include the abstract classes i.e. _FeatureCatalog and _FeatureType

**Comment by jetgeo** [comment]
The abstract classes for modularization is not included in the conceptual model. I guess it could be a best practice to have them in the implementation model.

**Comment by DaveDanko** [comment]
can we close this issue then?

**Comment by jetgeo** [comment]
As far as I'm concerned: yes. Ted or Steve will have to open it again if they disagree.
