### ISSUE TITLE
Stereotype "Abstract"

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19110#7]
Stereotype "Abstract" is used for several classes. This is unnecessary, they are already abstract because the class name are in Italic. I have changed this, but it can be reverted if you disagree. For CT_Catalogue, this cannot be changed, since it is in 19139.

**Comment by DaveDanko** [comment]
Personally I like the use of the stereotype "Abstract" the use of italics is too subtle and I miss it sometimes. But In light of trying to close all the issues I would say it doesn't matter.

**Comment by jetgeo** [comment]
Ok, so I'm closing this issue and keep it the way it is now, with stereotype "Abstract" only for CT_Catalogue. I see your point concerning readability Dave, but it is superfluous with both the stereotype and the italic font.
